### ISSUE TITLE
Incompatibility between version 10.2.6 and five-bells-ledger version 19

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-bells#111]
Currently, we can probably expect all five-bells-ledger instances to run version 19.4.2, which [means they use](https://github.com/interledgerjs/five-bells-ledger/blob/v19.4.2/package.json#L40) version 21.0.2 of five-bells-shared. This means the `execution_condition` field in FiveBellsTransfer objects [should start with `cc:`](https://github.com/interledgerjs/five-bells-shared/blob/v21.0.2/schemas/Condition.json)

Yet, ilp-plugin-bells version 10.2.6 [is not prepending this prefix](https://github.com/interledgerjs/ilp-plugin-bells/blob/v10.2.6/src/lib/plugin.js#L491) to the base64 `executionCondition` that is [coming from the plugin interface](https://github.com/interledger/rfcs/blob/e81d26c644b983b0db07a7e5d2f795703c6bdb5e/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#example-1)

I'm still looking for ways to confirm that this is actually what happened, but it seems that this incompatibility was not detected by our integration tests (they only look at the latest version of each component, not on the version of each component that is currently used by ilp-kit), and that this is what brought down the Interledger community network. :/

**Comment by emschwartz** [comment]
I don't think that was an incompatibility because the old ledger plugin interface specified that the execution conditions should have the `cc:` prefix. Everything was based on Crypto Conditions until we decided to switch to use the plain base64-encoded sha256 hash as the condition in the ledger plugin interface and the Crypto Conditions v2 (implemented by `five-bells-condition` v5) in the `five-bells-ledger`.

**Comment by michielbdejong** [comment]
Right, so then we should consider https://github.com/interledger/rfcs/blob/f1bed088b10f8c2f59370d19e8093074acfe4e0d/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#sendTransfer to be the current live version, maybe. I'll think about it some more.

**Comment by michielbdejong** [comment]
This was fixed with the release of ilp-kit v2
