### ISSUE TITLE
README out of date re ilp-core vs ilp

### ISSUE THREAD

**Issue by willclarktech** [interledgerjs/ilp-plugin-bells#133]
Unsure which one to use

**Comment by emschwartz** [comment]
Use `ilp`, `ilp-core` is in the process of being deprecated

**Comment by michielbdejong** [comment]
I'm fixing this here: https://github.com/interledgerjs/ilp-plugin-bells/pull/134#discussion_r120346425

**Comment by michielbdejong** [comment]
This was fixed, thanks for reporting!
