### ISSUE TITLE
Emitted transfers should use ILP address for account field

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-plugin-bells#25]
`.send` now expects the `account` field as an ILP address. Transfers emitted from events should translate the `five-bells-ledger` account URL into an ILP address ([here](https://github.com/interledger/js-ilp-plugin-bells/blob/master/src/lib/plugin.js#L405))

**Comment by justmoon** [comment]
@sentientwaffle This is a blocker for trustline settlement over FBL and presumably it's also a blocker for making any other plugins because the connector expects the current plugin-bells behavior.
