### ISSUE TITLE
getAccount should return a Promise

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-plugin-bells#26]
At least according to the spec: https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#getaccount

It should probably throw/reject if the plugin isn't connected

**Comment by sentientwaffle** [comment]
Resolved by https://github.com/interledger/js-ilp-plugin-bells/pull/27
