### ISSUE TITLE
sync up plugin with latest version of RFC-4

### ISSUE THREAD

**Issue by diminator** [interledgerjs/ilp-plugin-bells#30]
Maybe this is already in progress, but didn't see any issue/PR related:

The plugin is currently outdated compared to [RFC-4](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md)

main actions:
- [x] remove the connectors logic
- [ ] handle the events 

cc @justmoon @adrianhopebailie @emschwartz

**Comment by emschwartz** [comment]
It looks like the connector still uses this function so this logic should be changed: https://github.com/interledger/five-bells-connector/blob/master/src/lib/route-broadcaster.js#L84

**Comment by emschwartz** [comment]
Created a ticket for removing the `getConnectors` call from `js-ilp-core`: https://github.com/interledger/js-ilp-core/issues/43

**Comment by sentientwaffle** [comment]
What does "handle the events" refer to?

**Comment by diminator** [comment]
The number of events was updated (and out of sync with the old version of the plugin).
See the full list of events [here](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#events)

**Comment by michielbdejong** [comment]
As far as I'm aware, this was achieved - please reopen if not.
