### ISSUE TITLE
Don't retry http requests forever

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-plugin-bells#73]
It seems like if you give the plugin an incorrect or malformatted URL to send a request to (e.g. `blah`), it will continue retrying the request forever. It may do it with an increasing backoff but it should have an absolute cutoff or some point when it will just give up.

**Comment by sentientwaffle** [comment]
A malformed URL should fail immediately. If the URL is valid, though, wouldn't giving up conflict with https://github.com/interledgerjs/ilp-connector/issues/248 (allowing the connector to start before the ledger).

**Comment by emschwartz** [comment]
Agreed that a malformed URL should fail immediately.

Good question about valid URLs. My first thought is that there should be _some_ limit to how long it will keep trying for. Alternatively, it could be configurable and if it wants the connector could set that higher?
